### ISSUE TITLE
Восстановить запуск приложения

### ISSUE THREAD

**Issue by Nelfimov** [AtlantisUnited/serenity#173]
### С чем связан запрос на фичу?

В текущем окружении (Node.js 19) проект не запускается. Необходимо аккуратно привести его в рабочее состояние.

### Расскажите как вы это себе видите

Важно стабилизировать проект, зафиксировав версии зависимостей, Node.js, и yarn бандла.

Сервисы должны запускаться как нативно, так и через `docker compose`.

### Репортер

- https://t.me/Unick_q

**Comment by OsirisAnubiz** [comment]
@Nelfimov
Я правильно понимаю, что критерии готовности для этой таски:
1. Зафиксированны зависимости по всему проекту
2. Обновлён бандл до последней версии
3. Все сервисы запускаются через `yarn workspace service-name dev` при версии `node` 19.9
4. В `docker-compose.yml` обновлены версии `node` до 19.9
5. `docker compose up` запукается без ошибок

**Comment by Nelfimov** [comment]
Критерий готовности один - гарантия запуска сейчас и в будущем.

**Comment by TorinAsakura** [comment]
статус?

**Comment by OsirisAnubiz** [comment]
@TorinAsakura 

> статус?

Пока не приступал

**Comment by Nelfimov** [comment]
@OsirisAnubiz выделяй пожалуйста пару часов ежедневно - надо восстановить

**Comment by OsirisAnubiz** [comment]
@Nelfimov у тебя когда-то была такая ошибка?

```shell
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for
/workspace/.yarn/__virtual__/@catalog-application-virtual-0d9fbb3c26/1/catalog/application/src/index.ts
```

Просто уже довольно долго пытаюсь понять в чём дело и пока в ступоре
Ошибка возникает при запуске `catalog-service` через `yarn workspace @catalog/service dev`

**Comment by TorinAsakura** [comment]
@OsirisAnubiz Это у тебя бабел/вебпак не может понять что ты ему пытаешься подсунуть. Ну сам посуди. Кто занимается парсингом/билдом тса?

**Comment by TorinAsakura** [comment]
@OsirisAnubiz Проблема с подбором нужных версий, кмк

**Comment by OsirisAnubiz** [comment]
Пока в ступоре.

1. Взял репозиторий, который точно работает, позаимствовал оттуда общие вещи `tsconfig`, `docker-compose`, бандл и т.д. При этом изменив необходимые вещи.
2. Оставил только `protos/catalog` и `protos/common`(модули небходимые для `catalog`) и `catalog`
3. Перевёл на `esm`
4. Обновил зависимости

Всё равно вылезает эта ошибка.

**Comment by TorinAsakura** [comment]
> @Nelfimov у тебя когда-то была такая ошибка?
> 
> ```shell
> TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for
> /workspace/.yarn/__virtual__/@catalog-application-virtual-0d9fbb3c26/1/catalog/application/src/index.ts
> ```
> 
> Просто уже довольно долго пытаюсь понять в чём дело и пока в ступоре Ошибка возникает при запуске `catalog-service` через `yarn workspace @catalog/service dev`

ну, смотри, эта ошибка возникет когда у тебя нода пытается читать ТС без посредника, значит где-то что-то сдохло в процессе компиляции/сборки/чтения, опять же возвращаясь к вопросу об вебпаке/тсц

**Comment by OsirisAnubiz** [comment]
> ну, смотри, эта ошибка возникет когда у тебя нода пытается читать ТС без посредника, значит где-то что-то сдохло в процессе компиляции/сборки/чтения, опять же возвращаясь к вопросу об вебпаке/тсц

Билд проходит без ошибок (`yarn service build`). Далее запуститься не может и падает с ошибкой. Проблема с тем, что собирается в итоге. Пока не нашёл из-за чего такая ситтуация

**Comment by TorinAsakura** [comment]
@OsirisAnubiz Ну так ты посмотри что в итоге yarn build собирает

**Comment by OsirisAnubiz** [comment]
> Ну так ты посмотри что в итоге yarn build собирает

Я уже смотрел и мне это дало не слишком много. В сгенерированном `index.js` упоминаются `.ts` файлы, которых по идее не должно быть, но я не понимаю, почему возникает такое странное поведение при том, что я взял всё из проекта в котором всё работает. Завтра попробую с CommonJS сделать.

**Comment by TorinAsakura** [comment]
@OsirisAnubiz А ярн стоит свежий? А структура проекта соответствует той, что сейчас заложена в последнем ярне?

**Comment by OsirisAnubiz** [comment]
> А ярн стоит свежий? А структура проекта соответствует той, что сейчас заложена в последнем ярне?

1. Ярн пробовал тот, который самый свежий и тот, который в проекте точно рабочем.
2. Структуру я сильно не менял. `tsconfig.json` взят из рабочего проекта, `package.json` сделал с теми зависимостями, которые бандлу нужны. `.yarnrc.yml` тоже взят из рабочего с убранными расширениями. Речь идёт о том, что структура дирректорий тоже должна меняться?

**Comment by TorinAsakura** [comment]
@OsirisAnubiz Ну так ты загляни во внутрь билда. Исходники ведь открыты

**Comment by OsirisAnubiz** [comment]
> Ну так ты загляни во внутрь билда. Исходники ведь открыты

Имеется ввиду в бандл?

**Comment by TorinAsakura** [comment]
@OsirisAnubiz Какой ещё бандл?! В репу райдзина загляни и посмотри куда смотрит билд при сборке проекта!

**Comment by OsirisAnubiz** [comment]
Нет необходимости в определённой структуре дирректорий

**Comment by Nelfimov** [comment]
@OsirisAnubiz в какой ветке работаешь? Актуализируй

**Comment by OsirisAnubiz** [comment]
@Nelfimov
> в какой ветке работаешь? Актуализируй

`fix/app-startup3` там правда удалял некоторые диры, поэтому не надо пожалуйста мёржить в `app-startup`

**Comment by Nelfimov** [comment]
@OsirisAnubiz дополнил ветку:
- обновил зависимости
- обновил yarn.lock
- исправил `skipLibCheck`
- начал править чеки

99% что не запускается из-за ошибок тайпчека - исправь их. Там точно используется старый апи у терминуса

**Comment by OsirisAnubiz** [comment]
@Nelfimov даже если исправить все проблемы тайпчека и линта, то будет такая же ошибка

**Comment by Nelfimov** [comment]
прикреплено 2 ветки - какая из них?

**Comment by OsirisAnubiz** [comment]
@Nelfimov `fix/app-startup3` правда там удалено всё кроме `catalog` и много чего закоментированно, но сейчас у меня цель, чтобы хотя бы как-то запустился один сервис

**Comment by OsirisAnubiz** [comment]
@Nelfimov возможно мне стоит постепенно переписывать, но с нуля?

**Comment by Nelfimov** [comment]
@OsirisAnubiz пока оставь, я позже посмотрю сам

**Comment by Nelfimov** [comment]
@OsirisAnubiz можешь продолжать.

Косяк был в том, что зависимости у энтрипоинта работают по такому правилу:
- `dependencies` - то что не будет включено в бандл. Ожидается, что библиотеки доступны глобально. Смотри пример у наших новых воркеров для `picture` в rees46. Там в обычных зависимостях сидит `sharp`, потому что мы прикладываем его в образ докера
- `devDependencies` - то что будет включено в бандл

Это относится только к энтрипоинтам. В коде бандла это [находится тут](https://github.com/atls/raijin/blob/master/code/code-service/src/webpack.externals.ts)

**Comment by OsirisAnubiz** [comment]
Не получилось запустить, пока вылезает ошибка `Critical dependency: the request of a dependency is an expression`. По идее это ошибка вебпака.

Нашёл [issue](https://github.com/i18next/next-i18next/issues/1545) по этому поводу, но он не помог. По идее можно исправить обходным путём указав `exprContextCritical: false` в конфиге вебпака, но это не решение.

Ошибка возникает в:
- [optional-require.ts](https://github.com/nestjs/nest/blob/master/packages/core/helpers/optional-require.ts) в nestjs core
- [load-adapter.ts](https://github.com/nestjs/nest/blob/master/packages/core/helpers/load-adapter.ts) в nestjs core
- [server-grpc.ts](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-grpc.ts) в nestjs microservices
- [client-grpc.ts](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-grpc.ts) в nestjs microservices
- [load-package.util.ts](https://github.com/nestjs/nest/blob/master/packages/common/utils/load-package.util.ts) в nestjs common
...
- [lib/view.js](https://github.com/expressjs/express/blob/master/lib/view.js) в express

Пока не понял в чём проблема

**Comment by Nelfimov** [comment]
@OsirisAnubiz смотри в сторону протосов и как с ними работают. За пример более современного подхода можешь взять:
- https://github.com/candify-tech/web/tree/master/vacancy/server/protos/vacancy

Менее современный:
- https://github.com/delta-doc/web/tree/master/users/protos/users

Основная разница в генерации ts кода из прото файлов.

Еще очень страшная штука `ts-node`. Кажется будто она уже лишняя на сегодняшний день

**Comment by OsirisAnubiz** [comment]
@Nelfimov как можно получить путь до дирректории с зависимостями, чтобы можно было запустить бинарник? `yarn bin ts-proto` не работает. (не могу найти вариант)

**Comment by Nelfimov** [comment]
Не совсем понятен вопрос.

Если ты хочешь временно что то выполнить, то `yarn dlx...`

Если что то есть в зависимостях, напр `jest`, то будет `yarn jest ...`

**Comment by OsirisAnubiz** [comment]
> Не совсем понятен вопрос.
> 
> Если ты хочешь временно что то выполнить, то `yarn dlx...`
> 
> Если что то есть в зависимостях, напр `jest`, то будет `yarn jest ...`

`protoc --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto ...`

Мне нужно нечто подобное запихнуть в `scripts` в `package.json`, чтобы сгенерировать `.ts` файлы из `.proto` файлов, но мне для этого нужен путь до `.bin` в `node_modules`, но `node_modules` у нас нет, поэтому вот такой вопрос возникает.

**Comment by Nelfimov** [comment]
В случае `yarn` путей нет, да и остальные пакетные менеджеры по моему уже отказались от указания пути до исполнительного файла. Вот тебе пример для скрипта:

https://github.com/candify-tech/web/blob/master/applicant/server/protos/applicant/package.json#L17

**Comment by OsirisAnubiz** [comment]
@Nelfimov у тебя была когда-то ситтуация, что `yarn unplug` не отрабатывает в полной мере?

Тоесть вроде в `.yarn/unplugged` появился пакет, но не полностью.
Сделал `yarn unplug ts-proto`, но в `.yarn/unplugged/ts-proto-npm-...` не все файлы и из-за этого не может заработать. Если быть точнее то должна появиться дира `build`, где все файлы, а её там нет, только `protoc-gen-ts_proto`.

![image](https://github.com/user-attachments/assets/73928421-0420-412a-b79f-11b5233b8367)
![image](https://github.com/user-attachments/assets/4e42b828-e8e3-439d-ac8c-1a696ee39820)

**Comment by Nelfimov** [comment]
@OsirisAnubiz 

1. в ветке `fix/app-startup3` `ts-proto` нет
2. локально, если `ts-proto` поставить и анплаг, то у меня все есть:
    ![image](https://github.com/user-attachments/assets/253a0a8d-73df-416f-a662-44a1ba318e20)
<details><summary>Details</summary>
<p>

```shell
yarn add ts-proto
yarn why ts-proto
└─ serenity@workspace:.
   └─ ts-proto@npm:2.6.1 (via npm:2.6.1)
yarn unplug ts-proto
```

</p>
</details> 

У тебя свой вим, проверяй свои плагины по работе с фс. Возможно, они игнорируют папки `build`. Проверяй через `ls`

**Comment by iwwwanow** [comment]
#### Что сделано:
- пытаюсь запустить `@catalog/service` в `dev` режиме
- есть ошибка импорта cjs - `SyntaxError: Cannot use 'import.meta' outside a module`
- проверял работу вебпака в raijin
- пробовал пропатчить
- ошибка не у typeorm, а у вложенной зависимости

#### Что дальше:
- пока из идей только замена orm

#### Актуальная ветка:
- https://github.com/atls/serenity/tree/fix/startup

<details><summary>Details</summary>
<p>

```console

<anonymous_script>:23
	? __WEBPACK_EXTERNAL_createRequire(import.meta.url)
	                                         ^^^^
SyntaxError: Cannot use 'import.meta' outside a module
    at ../../.yarn/unplugged/app-root-path-npm-3.1.0-9822bb2a96/node_modules/app-root-path/lib/resolve.js (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:22257:1)
    at __webpack_require__ (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:28098:32)
    at fn (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:28251:20)
    at module.exports (webpack-internal:///../../.yarn/unplugged/app-root-path-npm-3.1.0-9822bb2a96/node_modules/app-root-path/lib/app-root-path.js:5:16)
    at eval (webpack-internal:///../../.yarn/unplugged/app-root-path-npm-3.1.0-9822bb2a96/node_modules/app-root-path/index.js:5:18)
    at ../../.yarn/unplugged/app-root-path-npm-3.1.0-9822bb2a96/node_modules/app-root-path/index.js (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:22237:1)
    at __webpack_require__ (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:28098:32)
    at fn (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:28251:20)
    at eval (webpack-internal:///../../.yarn/unplugged/typeorm-virtual-73e70a05f0/node_modules/typeorm/connection/ConnectionOptionsReader.js:5:49)
    at ../../.yarn/unplugged/typeorm-virtual-73e70a05f0/node_modules/typeorm/connection/ConnectionOptionsReader.js (file:///home/ubuntu-operator/Projects/atls_serenity/catalog/service/dist/index.js:22775:1)
Node.js v22.14.0

```

</p>
</details>
